sudo: false
language: node_js

cache:
  directories:
    - node_modules

node_js:
  - 8

notifications:
  email: false

script:
  - yarn build
  - yarn test
  - yarn coverage

after_success:
  - yarn report-coverage

branches:
  only:
    - master
